export const TOP_CRYPTOCURRENCIES = [
  { value: 'BTC', label: 'Bitcoin (BTC)', icon: '₿' },
  { value: 'ETH', label: 'Ethereum (ETH)', icon: 'Ξ' },
  { value: 'USDT', label: 'Tether (USDT)', icon: '₮' },
  { value: 'BNB', label: 'Binance Coin (BNB)', icon: 'Ƀ' },
  { value: 'SOL', label: 'Solana (SOL)', icon: '◎' },
  { value: 'XRP', label: 'XRP (XRP)', icon: '✕' },
  { value: 'USDC', label: 'USD Coin (USDC)', icon: '$' },
  { value: 'ADA', label: 'Cardano (ADA)', icon: '₳' },
  { value: 'AVAX', label: 'Avalanche (AVAX)', icon: 'A' },
  { value: 'DOGE', label: 'Dogecoin (DOGE)', icon: 'Ð' },
  { value: 'DOT', label: 'Polkadot (DOT)', icon: '●' },
  { value: 'TRX', label: 'TRON (TRX)', icon: 'T' },
  { value: 'LINK', label: 'Chainlink (LINK)', icon: '⬡' },
  { value: 'MATIC', label: 'Polygon (MATIC)', icon: 'P' },
  { value: 'TON', label: 'Toncoin (TON)', icon: 'T' },
  { value: 'UNI', label: 'Uniswap (UNI)', icon: '🦄' },
  { value: 'ICP', label: 'Internet Computer (ICP)', icon: '∞' },
  { value: 'ATOM', label: 'Cosmos (ATOM)', icon: '⚛' },
  { value: 'LTC', label: 'Litecoin (LTC)', icon: 'Ł' },
  { value: 'BCH', label: 'Bitcoin Cash (BCH)', icon: '฿' },
  { value: 'ETC', label: 'Ethereum Classic (ETC)', icon: 'ξ' },
  { value: 'XLM', label: 'Stellar (XLM)', icon: '*' },
  { value: 'FIL', label: 'Filecoin (FIL)', icon: '⨎' },
  { value: 'NEAR', label: 'NEAR Protocol (NEAR)', icon: 'Ⓝ' },
  { value: 'XMR', label: 'Monero (XMR)', icon: 'ɱ' },
  { value: 'INJ', label: 'Injective (INJ)', icon: 'I' },
  { value: 'VET', label: 'VeChain (VET)', icon: 'V' },
  { value: 'OP', label: 'Optimism (OP)', icon: 'O' },
  { value: 'ALGO', label: 'Algorand (ALGO)', icon: 'A' },
  { value: 'RUNE', label: 'THORChain (RUNE)', icon: 'R' },
  { value: 'GRT', label: 'The Graph (GRT)', icon: 'G' },
  { value: 'AAVE', label: 'Aave (AAVE)', icon: 'A' },
  { value: 'IMX', label: 'Immutable X (IMX)', icon: 'I' },
  { value: 'THETA', label: 'Theta Network (THETA)', icon: 'Θ' },
  { value: 'XTZ', label: 'Tezos (XTZ)', icon: 'ꜩ' },
  { value: 'MKR', label: 'Maker (MKR)', icon: 'M' },
  { value: 'FLOW', label: 'Flow (FLOW)', icon: 'F' },
  { value: 'EGLD', label: 'MultiversX (EGLD)', icon: 'E' },
  { value: 'SAND', label: 'The Sandbox (SAND)', icon: 'S' },
  { value: 'MANA', label: 'Decentraland (MANA)', icon: 'M' },
  { value: 'APE', label: 'ApeCoin (APE)', icon: '🦍' },
  { value: 'CRO', label: 'Cronos (CRO)', icon: 'C' },
  { value: 'QNT', label: 'Quant (QNT)', icon: 'Q' },
  { value: 'FTM', label: 'Fantom (FTM)', icon: 'F' },
  { value: 'KAVA', label: 'Kava (KAVA)', icon: 'K' },
  { value: 'NEO', label: 'NEO (NEO)', icon: 'N' },
  { value: 'SNX', label: 'Synthetix (SNX)', icon: 'S' },
  { value: 'COMP', label: 'Compound (COMP)', icon: 'C' },
  { value: 'ZEC', label: 'Zcash (ZEC)', icon: 'ⓩ' },
  { value: 'DASH', label: 'Dash (DASH)', icon: 'D' }
]; 